/**********************************************************************/
* Name    : DWH.PUBLIC.FACT_RECORD_REQUESTS
*
* GITHUB File Name : DWH_FACT_RECORD_REQUESTS.sql
*
* Version :        1.1
*
* Details: <Short description about the table>
*
* Edit History :
*
*  Name               Ver     Date      JIRA Ticket      Comment
*  ------------------ ---    --------   ------------- --------------------
*
*  Tharun             1.0    11/14/25                 Initial
*  Sandhya            1.1    02/14/25                 Added new Field ADD_TS TIMESTAMP_NTZ(9),ADD_USER VARCHAR(20), MOD_TS TIMESTAMP_NTZ(9), MOD_USER VARCHAR(20) and drop one field UPDATED_DATE
/**********************************************************************/

/*
create TABLE FACT_RECORD_REQUESTS (
	RECORD_REQUESTS_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	RRQ_ID NUMBER(11,0),
	RECORD_TYPE_AV_ID VARCHAR(10),
	RECORD_TYPE_DESC VARCHAR(2000),
	RECORD_NAME VARCHAR(50),
	REQUESTOR_EMAIL_ADDRESS VARCHAR(80),
	CAS_CAS_ID NUMBER(11,0),
	REQUEST_RECEIVED_DATE TIMESTAMP_NTZ(9),
	REQUEST_DUE_DATE TIMESTAMP_NTZ(9),
	RECORD_SENT_DATE TIMESTAMP_NTZ(9),
	RECORD_STATUS_DATE TIMESTAMP_NTZ(9),
	RECORD_STATUS_CODE_AV_ID VARCHAR(10),
	RECORD_STATUS_DESC VARCHAR(2000),
	REQUEST_TYPE_AV_ID VARCHAR(10),
	REQUEST_TYPE_DESC VARCHAR(2000),
	REQUESTOR_TYPE_AV_ID VARCHAR(10),
	REQUESTOR_TYPE_DESC VARCHAR(2000),
	REQUESTOR_NAME VARCHAR(50),
	RECORD_ID NUMBER(11,0),
	REQUESTING_COURT_ORGN_ID NUMBER(11,0),
	REQUESTING_COURT_ORGN_NAME VARCHAR(2000),
	RECORD_DISTR_METHOD_CODE_AV_ID VARCHAR(10),
	RECORD_DISTR_METHOD_DESC VARCHAR(2000),
	PREFERRED_DISTR_METHOD_CODE_AV_ID VARCHAR(10),
	PREFERRED_DISTR_METHOD_DESC VARCHAR(2000),
	FILE_LOCATION VARCHAR(500),
	TOTAL_PAGES NUMBER(11,0),
	REQUESTOR_PHONE VARCHAR(20),
	REQUESTOR_ADDRESS VARCHAR(200),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	primary key (RECORD_REQUESTS_ID)
);

*/

/*Ver No: 1.1   02/14/25*/
ALTER TABLE FACT_RECORD_REQUESTS ADD COLUMN ADD_TS TIMESTAMP_NTZ(9);
ALTER TABLE FACT_RECORD_REQUESTS ADD COLUMN ADD_USER VARCHAR(20);
ALTER TABLE FACT_RECORD_REQUESTS ADD COLUMN MOD_TS TIMESTAMP_NTZ(9);
ALTER TABLE FACT_RECORD_REQUESTS ADD COLUMN MOD_USER VARCHAR(20);

ALTER TABLE FACT_RECORD_REQUESTS DROP COLUMN UPDATED_DATE

-- Query for inserting the data in newly added columns
UPDATE FACT_RECORD_REQUESTS FRR
SET 
    FRR.ADD_TS = RR.ADD_TS, 
    FRR.MOD_TS = RR.MOD_TS, 
    FRR.ADD_USER = RR.ADD_USER, 
    FRR.MOD_USER = RR.MOD_USER
FROM T_RECORD_REQUESTS RR
WHERE FRR.RRQ_ID = RR.RRQ_ID;




